"""
PerfTrace to Perfetto JSON Converter
--------------------------------------
This tool converts a raw binary trace file generated by the PerfTrace C library 
into a JSON format that can be visualized using the Google Perfetto UI (https://ui.perfetto.dev/).

Usage Examples:
1. Standard Usage (1:1 time mapping):
   python tool_perf_trace.py my_trace.bin output.json

2. Hardware Specific Modifiers:
   Some hardware cores run at different clock speeds, meaning their timer ticks need 
   to be scaled to match a universal timebase (e.g., nanoseconds).
   You can provide core-specific multipliers using the --multipliers flag:
   
   python tool_perf_trace.py my_trace.bin output.json --multipliers "1:8,2:8,3:10,4:10"
   
   (This multiplies the time value of cores 1 & 2 by 8, and cores 3 & 4 by 10).
   
   Alternatively, if you only have a single core (or all your cores run at the same speed), 
   you can pass a single global multiplier:
   python tool_perf_trace.py my_trace.bin output.json --multipliers 10
"""

import pandas as pd  # type: ignore
import json
import numpy as np
import os
import sys
import argparse

def binary_to_hex32(input_file, output_file):
    if not os.path.isfile(input_file):
        print(f"Input file '{input_file}' not found.")
        return False

    with open(input_file, "rb") as bin_file, open(output_file, "w") as dat_file:
        while True:
            chunk = bin_file.read(4)
            if not chunk:
                break
            if len(chunk) < 4:
                print(f"Incomplete 4-byte chunk: {chunk.hex()}")
                break
            dat_file.write(f"{chunk[::-1].hex().upper()}\n")  # Little-endian
    return True

def main():
    parser = argparse.ArgumentParser(
        description="Convert PerfTrace binary to JSON for visualization in Perfetto UI.",
        epilog="Example:\n  python tool_perf_trace.py trace.bin out.json --multipliers '1:8,2:8,3:10'",
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument("input_binary", help="Path to input .dat or binary file (e.g., trace.bin)")
    parser.add_argument("output_json", help="Path to output .json file (e.g., output.json)")
    parser.add_argument("--multipliers", default="", help="Optional hardware clock scalers in core_id:multiplier format, or a single global multiplier.\nExamples: 1:8,2:8  OR just  8")
    args = parser.parse_args()

    input_bin = args.input_binary
    output_json = args.output_json
    dat_file = input_bin + ".dat"
    csv_file = input_bin + ".csv"

    core_mults = {}
    global_mult = 1
    if args.multipliers:
        if ':' not in args.multipliers:
            # Single global multiplier provided for all cores (e.g. single-core mode)
            global_mult = int(args.multipliers.strip())
        else:
            # Core specific multipliers
            for pair in args.multipliers.split(','):
                if ':' in pair:
                    cid, mult = pair.split(':')
                    core_mults[int(cid.strip())] = int(mult.strip())

    # Convert binary to .dat
    if not binary_to_hex32(input_bin, dat_file):
        return

    # Step 2: Process .dat into .csv
    dat_size = 4
    records = []

    wrap_offsets = {}
    last_times = {}

    with open(dat_file, "r", encoding="utf-8") as f:
        row = []
        while True:
            for _ in range(dat_size):
                line = f.readline().strip()
                if line:
                    row.append(line)
            if row:
                fun_addr = row[0]
                time_raw = int(row[1], 16)
                context_id = row[2]
                raw_event = int(row[3], 16)
                event_id = (raw_event >> 16) & 0xFFFF
                core_id = raw_event & 0xFFFF

                # Initialize per-core wrap and last time
                if core_id not in wrap_offsets:
                    wrap_offsets[core_id] = 0
                    last_times[core_id] = 0

                # Handle wrapping per core
                if time_raw < last_times[core_id]:
                    wrap_offsets[core_id] += (1 << 32)

                time = wrap_offsets[core_id] + time_raw
                # Apply configured time multiplier for this core
                if core_id in core_mults:
                    time = time * core_mults[core_id]
                else:
                    time = time * global_mult

                last_times[core_id] = time_raw

                records.append([core_id, fun_addr, time, context_id, event_id])
                row = []
            if not line:
                break

    df = pd.DataFrame(records, columns=["core_id", "fun_addr", "time", "context_id", "event"])
    df["event"] = df["event"].replace({3: 1, 4: 2})
    df["context_id"] = df["context_id"].astype(str)
    df["fun_addr"] = df["fun_addr"].astype(str)

    df.to_csv(csv_file, index=False)  # to generate csv file

    # Step 3: Stack and trace event handling
    cores = sorted(df["core_id"].unique())
    stack = {core: [] for core in cores}
    plot = {core: [] for core in cores}
    preempt = {core: [] for core in cores}

    for i in range(len(df)):
        core = df.at[i, "core_id"]
        row = df.iloc[i]
        if row["event"] == 1:
            if stack[core]:
                duration = row["time"] - stack[core][-1][-1]
                plot[core].append([*stack[core][-1][:3], duration, stack[core][-1][-1]])
            stack[core].append([row["core_id"], row["context_id"], row["fun_addr"], row["time"]])
        elif row["event"] == 2 and stack[core]:
            duration = row["time"] - stack[core][-1][-1]
            plot[core].append([*stack[core][-1][:3], duration, stack[core][-1][-1]])
            x = stack[core].pop()
            if stack[core]:
                preempt[core].append([*stack[core][-1][:3], duration, x[-1]])
                stack[core][-1][-1] = row["time"]

    # Step 4: Build JSON for Perfetto
    trace_events = []
    pid = 1

    trace_events.append({
        "name": "Running Track", "ph": "M", "pid": pid,
        "cat": "track_event", "args": {"state": "Running"},
        "cname": "background_goldenrod"
    })

    for core in cores:
        trace_events.append({
            "name": "process_name", "ph": "M", "pid": core,
            "args": {"name": f"Core{core}"}
        })
        for ctx in df[df["core_id"] == core]["context_id"].unique():
            trace_events.append({
                "name": "thread_name", "ph": "M", "pid": core, "tid": ctx,
                "args": {"name": f"Context {ctx}"}
            })

    for core in cores:
        for item in plot[core]:
            trace_events.append({
                "name": "[Running] " + item[2],
                "ph": "X",
                "ts": int(item[4]),
                "dur": int(item[3]),
                "pid": int(item[0]),
                "tid": item[1],
                "args": {"state": "Running"},
                "track": "Running Track"
            })

    trace_events.append({
        "name": "Runnable Track", "ph": "M", "pid": pid,
        "cat": "track_event", "args": {"state": "Runnable"},
        "cname": "background_light_blue"
    })

    for core in cores:
        for item in preempt[core]:
            trace_events.append({
                "name": "[Runnable] " + item[2],
                "ph": "X",
                "ts": int(item[4]),
                "dur": int(item[3]),
                "pid": int(item[0]),
                "tid": item[1],
                "args": {"state": "Runnable"},
                "track": "Runnable Track"
            })

    def convert_numpy(obj):
        if isinstance(obj, dict):
            return {k: convert_numpy(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [convert_numpy(x) for x in obj]
        elif isinstance(obj, (np.integer, np.floating)):
            return obj.item()
        return obj

    with open(output_json, "w") as f:
        json.dump({"traceEvents": convert_numpy(trace_events), "displayTimeUnit": "ns"}, f, separators=(",", ":"))

    print(f"Perfetto JSON written to {output_json}")

if __name__ == "__main__":
    main()